### ISSUE TITLE
Can't add or login to microsoft accounts

### ISSUE THREAD

**Issue by LordTenebris17** [The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher#53]
You can't login to Microsoft accounts or can add them. (can login to some of the Mojang accounts that haven't got migration request)
Mod doesn't make Minecraft to crash just doesn't make the job, tried to login on multiple Microsoft accounts none of them worked.

1. Launch Minecraft.
2. Press İn Game Account Switcher Mod Button.
3. Press add account button.
4. Press Microsoft button.
5. Accept Terms of services of Xbox.
6. Getting an error and not adding or logging into account

Screen shot of the issue : https://gyazo.com/7825a7dea1bedd0b0f77f344e616483c

Minecraft Version : 1.16.5 
İn Game Account Switcher Mod Version : 7.1.3
Loader Type : Fabric
Loader Version : 0.11.6
Fabric Api : 0.37.1

**Comment by ruben1PvP** [comment]
I opened almost a month before the same issue as you, but with Forge. 
P0keDev responded saying I needed to specify the Java Runtime in the Launcher, and as I did that the problem was solved.
Check it if you want
https://github.com/The-Fireplace-Minecraft-Mods/In-Game-Account-Switcher/issues/51

**Comment by VidTu** [comment]
The easiest solution for this problem could be "drop support for old Java 8 versions", but Mojang [provides outdated Java 8](https://launchermeta.mojang.com/v1/products/java-runtime/2ec0cc96c44e5a76b9c8b7c39df7210883d12871/all.json), especially for Windows. (`windows-x64.jre-legacy.version.name`=**8u51** released in [2015](https://www.java.com/releases/))

The temporary fix is updating your Java and selecting it in the launcher.

###### TODO for fixing this: Use something like [this](https://github.com/MinecraftForge/Installer/blob/5d8bc959d2cca9424b7fe37a93f74f567b575fa3/src/main/java/net/minecraftforge/installer/FixSSL.java#L59) in the IAS.

**Comment by bstar16** [comment]
what if you cant change to newer versions because of pc, this is why mojang still uses 8u51. i know it can be fixed cause a client i use fixed it without me having to change my java

**Comment by LordTenebris17** [comment]
bstar16 righy, somehow other client's account switching mods working perfectly and they don't requiring uptading java or such.

**Comment by LordTenebris17** [comment]
> The easiest solution for this problem could be "drop support for old Java 8 versions", but Mojang [provides outdated Java 8](https://launchermeta.mojang.com/v1/products/java-runtime/2ec0cc96c44e5a76b9c8b7c39df7210883d12871/all.json), especially for Windows. (`windows-x64.jre-legacy.version.name`=**8u51** released in [2015](https://www.java.com/releases/))
> 
> The temporary fix is updating your Java and selecting it in the launcher.
> 
> ###### TODO for fixing this: Use something like [this](https://github.com/MinecraftForge/Installer/blob/5d8bc959d2cca9424b7fe37a93f74f567b575fa3/src/main/java/net/minecraftforge/installer/FixSSL.java#L59) in the IAS.

**Comment by LordTenebris17** [comment]
> The easiest solution for this problem could be "drop support for old Java 8 versions", but Mojang [provides outdated Java 8](https://launchermeta.mojang.com/v1/products/java-runtime/2ec0cc96c44e5a76b9c8b7c39df7210883d12871/all.json), especially for Windows. (`windows-x64.jre-legacy.version.name`=**8u51** released in [2015](https://www.java.com/releases/))
> 
> The temporary fix is updating your Java and selecting it in the launcher.
> 
> ###### TODO for fixing this: Use something like [this](https://github.com/MinecraftForge/Installer/blob/5d8bc959d2cca9424b7fe37a93f74f567b575fa3/src/main/java/net/minecraftforge/installer/FixSSL.java#L59) in the IAS.

Oh but thanks for that fix i just tried to do it and now mod working properly thank you very much! For whoever don't know how to change minecraf java version can learn from here : https://minecrafthopper.net/help/guides/changing-java-version/

**Comment by LordTenebris17** [comment]
Also i don't know why but i added another account on account switcher and logged into that and when i wanted to switch my first account that i launched Minecraft with it it didn't let me to login on that account so i had to delete it from list and add it again with Microsoft button.

**Comment by VidTu** [comment]
Will be pinned until fixed in older versions of Java.

**Comment by VidTu** [comment]
This should be now fully fixed in 7.2.0. If not, open a new issue.

**Comment by Ruochenfu2011** [comment]
Still not fix using Javahome = 1.8.0_333,(tell me if im using the wrong java version)
Minecraft 1.8
(using curseforge, im not sure if it change the version of java)
